In [2]:
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
import sys
import requests
from io import BytesIO
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
from PIL import Image
import os
import numpy as np

sys.path.append('..')
from wc26_data import get_wc26_data, get_country_rankings, get_ids

/Users/chancetokubo/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [3]:
matches = get_ids('/Users/chancetokubo/bad.sports.metrics/matches.txt')
data = get_wc26_data(matches=matches)

Approximate time of data pulling completion: 144 seconds.
Dataframe Complete

In [4]:
rankings = get_country_rankings()

Dataframe complete.

In [7]:
data.head()

,Date,Group,Stage,TeamID,TeamName,TeamAbbr,Formation,IdMatch,GameNum,StatsId,...,SubstitutionsIn,SubstitutionsOut,TakeOnsCompleted,Threat,ThrowIns,TimePlayed,TopSpeed,TotalDistance,XG,YellowCards
0,2026-06-11T19:00:00Z,Group A,First Stage,43911,Mexico,MEX,4-1-2-3,400021443,1,151600,...,5.0,5.0,7.0,65.0,21.0,101.004683,33.307205,107310.437500,1.779373,1.0
1,2026-06-11T19:00:00Z,Group A,First Stage,43883,South Africa,RSA,5-3-2,400021443,1,151600,...,4.0,4.0,0.0,35.0,11.0,101.004683,34.370171,97060.179688,0.103336,2.0
2,2026-06-12T02:00:00Z,Group A,First Stage,43822,Korea Republic,KOR,3-4-3,400021441,2,151608,...,5.0,5.0,11.0,55.0,26.0,99.607383,35.170654,111805.359375,1.769696,1.0
3,2026-06-12T02:00:00Z,Group A,First Stage,43995,Czechia,CZE,5-2-3,400021441,2,151608,...,4.0,4.0,4.0,45.0,16.0,99.607383,33.999153,117628.406250,0.636732,0.0
4,2026-06-12T19:00:00Z,Group B,First Stage,43899,Canada,CAN,4-4-2,400021449,3,151614,...,5.0,5.0,8.0,68.0,32.0,100.330700,34.619015,111338.789062,1.494709,2.0

In [8]:
data = data.merge(rankings[['IdCountry', 'TotalPoints']], left_on='TeamAbbr', right_on='IdCountry', how='left').drop(columns='IdCountry')

opponent_elo = data.groupby('IdMatch')['TotalPoints'].transform(lambda x: x.iloc[::-1].values)
data['OpponentELO'] = opponent_elo

In [9]:
data.head()

,Date,Group,Stage,TeamID,TeamName,TeamAbbr,Formation,IdMatch,GameNum,StatsId,...,TakeOnsCompleted,Threat,ThrowIns,TimePlayed,TopSpeed,TotalDistance,XG,YellowCards,TotalPoints,OpponentELO
0,2026-06-11T19:00:00Z,Group A,First Stage,43911,Mexico,MEX,4-1-2-3,400021443,1,151600,...,7.0,65.0,21.0,101.004683,33.307205,107310.437500,1.779373,1.0,1700.984519,1418.211807
1,2026-06-11T19:00:00Z,Group A,First Stage,43883,South Africa,RSA,5-3-2,400021443,1,151600,...,0.0,35.0,11.0,101.004683,34.370171,97060.179688,0.103336,2.0,1418.211807,1700.984519
2,2026-06-12T02:00:00Z,Group A,First Stage,43822,Korea Republic,KOR,3-4-3,400021441,2,151608,...,11.0,55.0,26.0,99.607383,35.170654,111805.359375,1.769696,1.0,1612.547459,1481.485998
3,2026-06-12T02:00:00Z,Group A,First Stage,43995,Czechia,CZE,5-2-3,400021441,2,151608,...,4.0,45.0,16.0,99.607383,33.999153,117628.406250,0.636732,0.0,1481.485998,1612.547459
4,2026-06-12T19:00:00Z,Group B,First Stage,43899,Canada,CAN,4-4-2,400021449,3,151614,...,8.0,68.0,32.0,100.330700,34.619015,111338.789062,1.494709,2.0,1551.504089,1406.176640

In [ ]:
#pressure using finalthirdpitch control, possession, phaseaggregatefinalthird

In [38]:
mydata = data[['TeamName','TeamAbbr','IdMatch','TotalPoints','OpponentELO','FinalThirdPitchControl','Possession','PhaseAggregateFinalThird','XG','Goals']]

In [46]:
GoalvEGoal = mydata['Goals'] - mydata['XG']
mydata['GvEG'] = GoalvEGoal
mydata['GvEGS'] = GoalvEGoal / mydata['XG']

/var/folders/vl/tq28lccn1d19hq22zfhh94lc0000gn/T/ipykernel_68865/702340752.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mydata['GvEG'] = GoalvEGoal
/var/folders/vl/tq28lccn1d19hq22zfhh94lc0000gn/T/ipykernel_68865/702340752.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mydata['GvEGS'] = GoalvEGoal / mydata['XG']

In [48]:
GPMinFinalThird = mydata['Goals'] / mydata['PhaseAggregateFinalThird']
mydata['GPMFT'] = GPMinFinalThird

/var/folders/vl/tq28lccn1d19hq22zfhh94lc0000gn/T/ipykernel_68865/232542093.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mydata['GPMFT'] = GPMinFinalThird

In [49]:
mydata

,TeamName,TeamAbbr,IdMatch,TotalPoints,OpponentELO,FinalThirdPitchControl,Possession,PhaseAggregateFinalThird,XG,Goals,GvEG,GvEGS,GPMFT
0,Mexico,MEX,400021443,1700.984519,1418.211807,62.0,0.570936,10.756574,1.779373,2.0,0.220627,0.123991,0.185933
1,South Africa,RSA,400021443,1418.211807,1700.984519,34.0,0.360912,6.863084,0.103336,0.0,-0.103336,-1.000000,0.000000
2,Korea Republic,KOR,400021441,1612.547459,1481.485998,55.0,0.557826,13.772668,1.769696,2.0,0.230304,0.130138,0.145215
3,Czechia,CZE,400021441,1481.485998,1612.547459,41.0,0.341655,11.588785,0.636732,1.0,0.363268,0.570518,0.086290
4,Canada,CAN,400021449,1551.504089,1406.176640,67.0,0.528129,19.241495,1.494709,1.0,-0.494709,-0.330973,0.051971
5,Bosnia and Herzegovina,BIH,400021449,1406.176640,1551.504089,29.0,0.298916,4.765946,0.761922,1.0,0.238078,0.312471,0.209822
6,USA,USA,400021458,1688.534820,1488.048969,74.0,0.594737,21.856615,1.877016,4.0,2.122984,1.131042,0.183011
7,Paraguay,PAR,400021458,1488.048969,1688.534820,22.0,0.287417,6.794338,0.604615,1.0,0.395385,0.653944,0.147181
8,Qatar,QAT,400021447,1459.446908,1629.939343,18.0,0.287881,8.191307,0.518329,1.0,0.481671,0.929277,0.122081
9,Switzerland,SUI,400021447,1629.939343,1459.446908,79.0,0.587374,28.390107,3.141817,1.0,-2.141817,-0.681713,0.035224
10,Brazil,BRA,400021456,1765.340396,1755.616133,48.0,0.466898,11.077043,0.992151,1.0,0.007849,0.007911,0.090277
11,Morocco,MAR,400021456,1755.616133,1765.340396,48.0,0.451906,17.008033,1.330632,1.0,-0.330632,-0.248477,0.058796
12,Haiti,HAI,400021453,1277.668371,1518.768484,58.0,0.516316,18.616417,0.702218,0.0,-0.702218,-1.000000,0.000000
13,Scotland,SCO,400021453,1518.768484,1277.668371,38.0,0.404776,8.838030,0.912966,1.0,0.087034,0.095331,0.113147
14,Australia,AUS,400021463,1605.607419,1579.466142,15.0,0.270350,12.048136,0.985548,2.0,1.014452,1.029327,0.166001
15,Türkiye,TUR,400021463,1579.466142,1605.607419,83.0,0.628759,33.647919,1.661554,0.0,-1.661554,-1.000000,0.000000
16,Germany,GER,400021464,1743.544935,1286.996139,72.0,0.577956,23.242390,4.165321,7.0,2.834679,0.680543,0.301174
17,Curaçao,CUW,400021464,1286.996139,1743.544935,24.0,0.353217,8.537206,0.404172,1.0,0.595828,1.474195,0.117134
18,Netherlands,NED,400021470,1749.204090,1665.943996,60.0,0.548608,23.503748,0.629371,2.0,1.370629,2.177774,0.085093
19,Japan,JPN,400021470,1665.943996,1749.204090,37.0,0.374495,20.117094,0.338975,2.0,1.661025,4.900141,0.099418
20,Côte d'Ivoire,CIV,400021467,1568.623632,1570.761721,50.0,0.419375,21.641415,1.882395,1.0,-0.882395,-0.468762,0.046208
21,Ecuador,ECU,400021467,1570.761721,1568.623632,46.0,0.498733,10.631792,1.359632,0.0,-1.359632,-1.000000,0.000000
22,Sweden,SWE,400021474,1533.186308,1453.004172,42.0,0.473866,16.943872,2.091256,5.0,2.908744,1.390908,0.295092
23,Tunisia,TUN,400021474,1453.004172,1533.186308,54.0,0.426657,14.201836,0.341888,1.0,0.658112,1.924933,0.070413
24,Spain,ESP,400021482,1856.033671,1389.785087,91.0,0.656594,40.287548,2.262369,0.0,-2.262369,-1.000000,0.000000
25,Cabo Verde,CPV,400021482,1389.785087,1856.033671,7.0,0.254019,4.670464,0.130574,0.0,-0.130574,-1.000000,0.000000
26,Belgium,BEL,400021478,1733.934577,1570.668614,36.0,0.520000,23.170000,1.070000,1.0,-0.070000,-0.065421,0.043159
27,Egypt,EGY,400021478,1570.668614,1733.934577,23.0,0.380000,16.470000,0.810000,1.0,0.190000,0.234568,0.060716
28,Saudi Arabia,KSA,400021486,1435.000167,1661.949665,16.0,0.270980,8.319473,1.056545,1.0,-0.056545,-0.053519,0.120200
29,Uruguay,URU,400021486,1661.949665,1435.000167,80.0,0.633294,23.520514,1.502002,1.0,-0.502002,-0.334222,0.042516
30,IR Iran,IRN,400021476,1605.121289,1290.041403,54.0,0.433090,16.765009,1.854284,2.0,0.145716,0.078583,0.119296
31,New Zealand,NZL,400021476,1290.041403,1605.121289,41.0,0.452782,12.663202,1.473111,2.0,0.526889,0.357671,0.157938
32,France,FRA,400021490,1887.107625,1667.658416,57.0,0.493710,11.809316,1.615593,3.0,1.384407,0.856904,0.254037
33,Senegal,SEN,400021490,1667.658416,1887.107625,39.0,0.444536,10.926801,0.386067,1.0,0.613933,1.590224,0.091518
34,Iraq,IRQ,400021488,1426.532498,1577.184771,37.0,0.347060,9.382470,1.199913,1.0,-0.199913,-0.166606,0.106582
35,Norway,NOR,400021488,1577.184771,1426.532498,59.0,0.572034,10.713905,2.410916,4.0,1.589084,0.659120,0.373347
36,Argentina,ARG,400021496,1889.062265,1559.237599,30.0,0.446214,7.013091,1.584155,3.0,1.415845,0.893754,0.427771
37,Algeria,ALG,400021496,1559.237599,1889.062265,66.0,0.508247,16.154133,0.410713,0.0,-0.410713,-1.000000,0.000000
38,Austria,AUT,400021498,1612.855967,1372.286342,51.0,0.533376,13.914843,1.931259,3.0,1.068741,0.553391,0.215597
39,Jordan,JOR,400021498,1372.286342,1612.855967,45.0,0.330076,19.321847,0.531269,1.0,0.468731,0.882287,0.051755
40,Portugal,POR,400021502,1755.093610,1487.183182,75.0,0.688541,23.653854,0.566313,1.0,0.433687,0.765807,0.042276
41,Congo DR,COD,400021502,1487.183182,1755.093610,22.0,0.253498,13.692617,0.535296,1.0,0.464704,0.868125,0.073032
42,England,ENG,400021507,1847.677458,1695.210017,46.0,0.489938,9.959792,3.329283,4.0,0.670717,0.201460,0.401615
43,Croatia,CRO,400021507,1695.210017,1847.677458,50.0,0.435021,15.432827,0.817905,2.0,1.182095,1.445271,0.129594
44,Ghana,GHA,400021510,1380.707809,1505.328905,42.0,0.355833,11.308552,0.976224,1.0,0.023776,0.024355,0.088429
45,Panama,PAN,400021510,1505.328905,1380.707809,54.0,0.555484,13.073525,0.771292,0.0,-0.771292,-1.000000,0.000000
46,Uzbekistan,UZB,400021504,1444.481764,1712.604162,43.0,0.339443,8.997317,1.105400,1.0,-0.105400,-0.095350,0.111144
47,Colombia,COL,400021504,1712.604162,1444.481764,53.0,0.567009,12.520446,1.160670,3.0,1.839330,1.584714,0.239608