In [1]:
import pandas as pd
import sys
sys.path.append('..')

In [ ]:
from wc26_data import get_wc26_data, get_country_rankings, get_ids
#import using wc26_data.py

/Users/chancetokubo/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [4]:
matches = get_ids('/Users/chancetokubo/bad.sports.metrics/matches.txt')
my_data = get_wc26_data(matches=matches)

Approximate time of data pulling completion: 108 seconds.
Dataframe Complete

In [5]:
my_data.tail()

,Date,Group,Stage,TeamID,TeamName,TeamAbbr,Formation,IdMatch,GameNum,StatsId,...,SubstitutionsIn,SubstitutionsOut,TakeOnsCompleted,Threat,ThrowIns,TimePlayed,TopSpeed,TotalDistance,XG,YellowCards
31,2026-06-16T01:00:00Z,Group G,First Stage,43978,New Zealand,NZL,4-4-2,400021476,15,151644,...,5.0,5.0,9.0,49.0,16.0,101.419750,32.360195,112902.718750,1.473111,0.0
32,2026-06-16T19:00:00Z,Group I,First Stage,43946,France,FRA,4-2-3-1,400021490,17,151656,...,2.0,2.0,13.0,54.0,9.0,105.881233,35.115707,120179.570312,1.615593,0.0
33,2026-06-16T19:00:00Z,Group I,First Stage,43879,Senegal,SEN,4-3-3,400021490,17,151656,...,5.0,5.0,8.0,46.0,21.0,105.881233,33.771500,116725.093750,0.386067,0.0
34,2026-06-16T22:00:00Z,Group I,First Stage,43818,Iraq,IRQ,4-4-2,400021488,18,151655,...,5.0,5.0,NaN,42.0,14.0,NaN,33.160000,113058.360000,0.600000,1.0
35,2026-06-16T22:00:00Z,Group I,First Stage,43961,Norway,NOR,4-1-2-3,400021488,18,151655,...,5.0,5.0,NaN,58.0,17.0,NaN,36.430000,118949.180000,1.640000,0.0

In [5]:
subset = my_data[['TeamName','TotalDistance','DistanceHighSpeedRunning','DistanceHighSpeedSprinting','DistanceJogging','DistanceLowSpeedSprinting','DistanceWalking']]
subset['%Slow'] = subset['DistanceWalking']/subset['TotalDistance']
subset['%Fast'] = (subset['DistanceHighSpeedRunning'] + subset['DistanceHighSpeedSprinting'])/subset['TotalDistance']

/var/folders/vl/tq28lccn1d19hq22zfhh94lc0000gn/T/ipykernel_40667/2439424740.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset['%Slow'] = subset['DistanceWalking']/subset['TotalDistance']
/var/folders/vl/tq28lccn1d19hq22zfhh94lc0000gn/T/ipykernel_40667/2439424740.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset['%Fast'] = (subset['DistanceHighSpeedRunning'] + subset['DistanceHighSpeedSprinting'])/subset['TotalDistance']

In [6]:
subset.sort_values(by="%Slow", ascending=False).head(1)

,TeamName,TotalDistance,DistanceHighSpeedRunning,DistanceHighSpeedSprinting,DistanceJogging,DistanceLowSpeedSprinting,DistanceWalking,%Slow,%Fast
18,Netherlands,102943.289062,12240.800781,1451.22998,40676.640625,4594.399902,43980.21875,0.427228,0.133006

In [7]:
subset.sort_values(by="%Fast", ascending=False).head(1)

,TeamName,TotalDistance,DistanceHighSpeedRunning,DistanceHighSpeedSprinting,DistanceJogging,DistanceLowSpeedSprinting,DistanceWalking,%Slow,%Fast
16,Germany,116216.09375,16171.019531,2425.949951,48943.589844,6327.640137,42347.890625,0.364389,0.160021

In [8]:
subset.sort_values(by='TotalDistance', ascending=False).head(1)
#on the original post, it was USA because it was posted before the France Game had concluded

,TeamName,TotalDistance,DistanceHighSpeedRunning,DistanceHighSpeedSprinting,DistanceJogging,DistanceLowSpeedSprinting,DistanceWalking,%Slow,%Fast
32,France,120179.570312,15676.839844,2824.290039,48833.03125,6989.080078,45856.332031,0.381565,0.153946

In [9]:
subset.sort_values(by='TotalDistance', ascending=True).head(1)

,TeamName,TotalDistance,DistanceHighSpeedRunning,DistanceHighSpeedSprinting,DistanceJogging,DistanceLowSpeedSprinting,DistanceWalking,%Slow,%Fast
1,South Africa,97060.179688,12432.0,1773.670044,37716.210938,5081.469727,40056.828125,0.412701,0.146359